FROM ubuntu:26.04

ARG DEBIAN_FRONTEND=noninteractive 

# Install basic packages
RUN apt update && apt install -y --no-install-recommends \
    software-properties-common \
    openssh-server \
    ca-certificates \
    wget \
    curl \
    ffmpeg \
    git \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Install NodeJS
RUN curl -fsSL https://deb.nodesource.com/setup_26.x | bash - && \
    apt install -y --no-install-recommends \
    nodejs=26.7.0-1nodesource1 \
    && rm -rf /var/lib/apt/lists/*
