FROM ubuntu:26.04

ARG DEBIAN_FRONTEND=noninteractive 

# Install basic packages
RUN apt update && apt install -y --no-install-recommends \
    software-properties-common \
    openssh-server \
    ca-certificates \
    wget \
    curl \
    ffmpeg \
    libimage-exiftool-perl \
    git \
    jq \
    xdg-utils \
    xz-utils \
    binutils \
    locales \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen en_US.UTF-8

RUN apt update && apt install -y --no-install-recommends \
    libnspr4 \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libdbus-1-3 \
    libxkbcommon0 \
    libgtk-3-0 \
    libatspi2.0-0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2t64 \
    libwayland-client0 \
    && rm -rf /var/lib/apt/lists/*

# Install NodeJS
RUN curl -fsSL https://deb.nodesource.com/setup_26.x | bash - && \
    apt install -y --no-install-recommends \
    nodejs=26.7.0-1nodesource1 \
    && rm -rf /var/lib/apt/lists/*
