import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { mkdtemp, readFile, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { before, describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'
import { promisify } from 'node:util'

import {
  createParamsType,
  generatePortableRouteContract,
  main,
  parseCliArgs,
  parseLeafRoutes,
  parsePublicRoutes,
  renderRegister
} from './generate-public-routes'

const routingDir = path.dirname(fileURLToPath(import.meta.url))

const tmpFile = async (name: string, content?: string) => {
  const filePath = path.join(await mkdtemp(path.join(tmpdir(), 'contract-')), name)
  if (content !== undefined) await writeFile(filePath, content, 'utf8')
  return filePath
}

const typegenSource = `// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/security/:token-id" | "/login";
  };
  "routes/toto.tsx": {
    id: "routes/toto";
    page: "/";
  };
  "routes/api/api.security.ts": {
    id: "routes/api/api.security";
    page: "/api/security/:token-id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": unknown;
  "routes/toto": typeof import("./app/routes/toto.tsx");
};`

describe('parseLeafRoutes', () => {
  it('extracts leaf routes and skips union-page layouts', () => {
    assert.deepEqual(parseLeafRoutes({ source: typegenSource }), [
      { id: 'routes/toto', page: '/', routeFile: 'routes/toto.tsx' },
      {
        id: 'routes/api/api.security',
        page: '/api/security/:token-id',
        routeFile: 'routes/api/api.security.ts'
      },
      { id: 'routes/login', page: '/login', routeFile: 'routes/login.tsx' }
    ])
  })
})

describe('parsePublicRoutes', () => {
  const listSource = `import type { PageOf } from '@workspace/shared/routing'
import type { Register } from 'react-router'

const publicRoutes = [
  '/api/security/:token-id',
  '/api/toto2',
  '/api/toto2'
] as const satisfies readonly PageOf<Register>[]`
  it('extracts pages in order and removes duplicates', () => {
    assert.deepEqual(parsePublicRoutes({ source: listSource }), [
      '/api/security/:token-id',
      '/api/toto2'
    ])
  })

  it('ignores other variables', () => {
    assert.deepEqual(
      parsePublicRoutes({
        source: `const otherRoutes = ['/ignored']\n${listSource}`
      }),
      ['/api/security/:token-id', '/api/toto2']
    )
  })

  it('allows an empty list', () => {
    assert.deepEqual(parsePublicRoutes({ source: `const publicRoutes: string[] = []` }), [])
  })

  it('rejects invalid lists', () => {
    assert.throws(
      () =>
        parsePublicRoutes({
          source: `const page = '/api/toto2'\nconst publicRoutes = [page]`
        }),
      /string literals/
    )
    assert.throws(() => parsePublicRoutes({ source: `const other = ['/x']` }), /no "publicRoutes"/)
    assert.throws(
      () => parsePublicRoutes({ source: `const publicRoutes = '/api/toto2'` }),
      /must be an array/
    )
  })
})

describe('createParamsType', () => {
  it('returns an empty object for static pages', () => {
    assert.equal(createParamsType('/'), '{}')
    assert.equal(createParamsType('/toto2-success'), '{}')
  })

  it('derives required, optional and multiple params', () => {
    assert.equal(
      createParamsType('/api/widgets/:widget-id'),
      `{\n        'widget-id': string\n      }`
    )
    assert.equal(
      createParamsType('/api/security/:token-id'),
      `{\n        'token-id': string\n      }`
    )
    assert.equal(createParamsType('/files/:path?'), `{\n        'path'?: string\n      }`)
    assert.equal(
      createParamsType('/orgs/:orgId/users/:userId'),
      `{\n        'orgId': string\n        'userId': string\n      }`
    )
  })
})

describe('parseCliArgs', () => {
  it('parses flag value pairs', () => {
    assert.deepEqual(parseCliArgs(['--app-dir', 'apps/x', '--register-name', 'XRegister']), {
      'app-dir': 'apps/x',
      'register-name': 'XRegister'
    })
  })

  it('ignores dangling flags and flag-like values', () => {
    assert.deepEqual(parseCliArgs(['--app-dir', '--output-file', 'out']), {
      'output-file': 'out'
    })
    assert.deepEqual(parseCliArgs(['--page-prefix']), {})
  })
})

describe('renderRegister', () => {
  it('renders the portable register file', () => {
    const rendered = renderRegister({
      registerName: 'DemoRegister',
      pages: [
        `    '/health': {
      params: {}
      searchParamsArgs: never
      actionArgs: never
      loaderResult: unknown
      actionResult: unknown
    }`
      ]
    })

    assert.equal(
      rendered,
      `type DemoRegister = {
  pages: {
    '/health': {
      params: {}
      searchParamsArgs: never
      actionArgs: never
      loaderResult: unknown
      actionResult: unknown
    }
  }
}

export type { DemoRegister }
`
    )
  })
})

describe('main', () => {
  it('throws the usage message when required flags are missing', async () => {
    await assert.rejects(main([]), /Usage: generate-public-routes/)
  })
})

describe('generatePortableRouteContract', () => {
  const centralAuthDir = path.resolve(routingDir, '../../../../apps/central-auth')
  const workspaceRoot = path.resolve(routingDir, '../../../..')

  before(async () => {
    try {
      await stat(path.join(centralAuthDir, '.react-router/types/+routes.ts'))
    } catch {
      const typegenBin = path.join(workspaceRoot, 'node_modules', '.bin', 'react-router')
      await promisify(execFile)(typegenBin, ['typegen'], { cwd: centralAuthDir })
    }
  })

  it('generates typed pages from central-auth', async () => {
    const outputFile = await tmpFile('central-auth.ts')

    await generatePortableRouteContract({
      appDir: centralAuthDir,
      outputFile,
      publicRoutes: path.join(centralAuthDir, 'app/public-routes.ts'),
      registerName: 'CentralAuthRegister'
    })

    const output = await readFile(outputFile, 'utf8')
    assert.ok(output.includes(`'/api/security/:token-id'`))
    assert.ok(output.includes(`'/api/toto2'`))
    assert.ok(output.includes(`'token-id': string`))
    assert.ok(output.includes('organization'))
    assert.ok(output.includes('actionResult: unknown'))
    assert.ok(output.includes('loaderResult: unknown'))
    assert.ok(!output.includes(`'/login': {`))
    assert.ok(!output.includes('ResultFor'))
    assert.ok(output.includes('export type { CentralAuthRegister }'))
  })

  it('rejects listed pages missing from typegen output', async () => {
    const listFile = await tmpFile('public-routes.ts', `const publicRoutes = ['/nope']`)
    const outputFile = await tmpFile('central-auth.ts')

    await assert.rejects(
      generatePortableRouteContract({
        appDir: centralAuthDir,
        outputFile,
        publicRoutes: listFile,
        registerName: 'CentralAuthRegister'
      }),
      /was not found in React Router typegen output/
    )
  })
})
